### ISSUE TITLE
Stellar mass distribution 

### ISSUE THREAD

**Issue by Andromedanita** [LSSTDESC/descqa#109]
The purpose of this issue is to understand the shape of the distribution of galaxy stellar masses in protoDC2 catalogues as we have been discussing this with @reneehlozek. In the previous version, there was a small bump at about 10^10 solar masses that was not obvious to me why it was there. In the most recent version, the bump is still there as well as another skewness at lower masses around 10^8 solar masses. Maybe this second bump is because that the peak of the distribution was about 10^8 solar masses in version 2 while the peak is currently at much lower masses around 10^(6-7) solar masses. The histograms are shown below:
![mstellar](https://user-images.githubusercontent.com/4367142/39027953-60716226-4422-11e8-9d9a-e03af656979c.png)

I checked the stellar mass distribution from SDSS galaxies from Maraston et al. 2013 that plotted the distributions for SDSS BOSS and CMASS galaxies that were fit with different templates. These distribution do not have any obvious bumps. The figures from the paper are shown below for BOSS and CMASS catalogues:
![sdss_mstellar](https://user-images.githubusercontent.com/4367142/39028131-0b016326-4423-11e8-90ce-b0272dbafc6c.jpg)

I also know that the CMASS galaxies are more biased toward higher mass galaxies but it would be good to know why protoDC2 galaxies peak at such small stellar masses.

**Comment by rmandelb** [comment]
@Andromedanita - the fact that protoDC2 has more galaxies at low stellar mass is a consequence of the fact that we are trying to simulate a sample that is very different in properties from the CMASS sample.  The CMASS number density is orders of magnitude lower than the much fainter galaxy sample in protoDC2, so the stellar mass distributions should look very different.  (Think of it another way: the CMASS sample goes down to an apparent magnitude of i<21.5 or so.  The protoDC2 catalog goes many magnitudes fainter than this, so the samples really should not look comparable in apparent magnitude, luminosity, stellar mass, redshift, etc.)

If you want to make a fair comparison, you could impose the CMASS sample magnitude and colors cuts on the protoDC2 catalog, and see whether the redshift and stellar mass distribution for CMASS and protoDC2 is comparable. This would be a rather interesting test.  And you will see when doing this that the vast majority of protoDC2 galaxies are eliminated because it's such a different sample.

**Comment by reneehlozek** [comment]
Thanks @rmandelb - it is good to know what an "apples with apples" comparison would be (so great idea about the cuts, I think this is a great thing for @Andromedanita to get on with next!). I am playing catch up so almost certainly missed a note on this, but was the shift in the distribution from v2 to v3 intentional?

**Comment by aphearin** [comment]
Thanks for the input, everyone. These changes from v2 to v3 are very much intentional. Between these two versions, we began a new approach in which empirical methods are used to fix the galaxy—halo connection, and Galacticus is treated as a galaxy library that we sample from. 

Your observation about the faint end of the SMF illustrates one manifestation of this change. After v2, the PHZ WG requested that fainter galaxies be included in the sample. 

There is a nice SMF test in DESCQA based on Moustakas+13 that might be a good place to look for quantitative comparison of v3 SMF to data.

**Comment by evevkovacs** [comment]
Please see https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-03-27_2&catalog=protoDC2&right=2018-03/2018-03-27_2/SMF_PRIMUS/protoDC2/SMF_protoDC2.png for the comparison of the stellar-mass function with PRIMUS data  for protoDC2 v3.  The same plot for the pre-release of protoDC2 v4  can be seen here: https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-04-12_24&catalog=proto-dc2_v4.0_test&right=2018-04/2018-04-12_24/SMF_PRIMUS/proto-dc2_v4.0_test/SMF_proto-dc2_v4.0_test.png.  The final release of v4 should not change the SMF significantly. The DESCQA test has the flexibility to work with other data sets, so if you would like to work on developing a variant with CMASS data please see the instructions on https://github.com/LSSTDESC/descqa/

**Comment by Andromedanita** [comment]
Thanks everyone for your useful comments.

**Comment by Andromedanita** [comment]
Your suggestion for applying a cut to the color similar to CMASS catalogue for protoDC2 was indeed correct @rmandelb . I applied a cut in i-band to protoDC2 galaxies and I see that only about 200,000 galaxies satisfy this condition out of the total of ~10 million galaxies in protoDC2 and the peak of the stellar mass distribution is shifted to much higher masses close to that of SDSS galaxies. Below is my histogram just to show this.

![mstellar_protodc2_cmass](https://user-images.githubusercontent.com/4367142/39449342-c55a41be-4c95-11e8-9b1d-5592f5c425aa.png)

Also, the redshift of these conditioned galaxies are lower than all of protoDC2 galaxies because protoDC2 goes deeper into magnitude than SDSS.

![redshift_protodc2_cmass](https://user-images.githubusercontent.com/4367142/39449520-4e8dc866-4c96-11e8-888b-506bab26c4e5.png)

**Comment by aphearin** [comment]
Great! Thanks for the hard work in testing the catalog, @Andromedanita!

**Comment by rmandelb** [comment]
Thanks for these plots!  That looks much better.

Note that if this is the 25 square degree catalog, then with 675 CMASS-like
galaxies detected, this corresponds to a density of 27 per square degree.
The actual CMASS density is closer to 100 per square degree according to
table 2 of http://adsabs.harvard.edu/abs/2016MNRAS.455.1553R .  I'm not
sure how much we want to worry about this, but it may point to a deficit of
massive red galaxies (though I realize that this might have been updated in
the latest protoDC2 v4).

**Comment by aphearin** [comment]
@rmandelb - There are no CMASS validations in DESCQA that I'm aware of, but I think this DESCQA plot comparing the latest release v4.4 of the protoDC2 shows that the stellar mass function is in good agreement with PRIMUS across mass and redshift. 

![smf_moustakas](https://user-images.githubusercontent.com/6951595/39998937-38bd6ec6-574d-11e8-8f3f-a51480aca228.png)

**Comment by rmandelb** [comment]
That does look good, but it might be something to do with the joint distribution of stellar mass and color rather than just stellar mass.  I think @Andromedanita was using v3, and colors of galaxies in clusters were one of the updates to v4, so I expect her results might change somewhat?

**Comment by aphearin** [comment]
Good point @rmandelb. The SMF for v3 was definitely deficient in high-mass galaxies at z >~0.5, regardless of color cut. This was one of the (many) modifications made between v3 to v4.4.

**Comment by rmandelb** [comment]
@Andromedanita - I was wondering, were you planning to turn your script that you used to produce the "CMASS" sample stellar mass distribution into a validation test that can be integrated into DESCQA?

I was thinking even a simple validation test that ignores the stellar mass distribution and just checks whether the CMASS-like sample has approximately the right number density would be interesting (in addition to the plot of the stellar mass function).

If you have questions about how to turn this into a test in DESCQA, @yymao would be able to answer your questions.  My sense is that you've already done nearly all of the work that would be needed (since you were able to make the plots above).

**Comment by reneehlozek** [comment]
I think this would be a great idea for @Andromedanita to implement, especially as you mention she's done almost all the work already!

**Comment by Andromedanita** [comment]
Thanks @aphearin and @rmandelb for the plots and the comments. I was using the latest released version available but that is v3. I asked Yao and he gave me instructions on how to access v4.4 and there is now v4.5 but these are not released yet. I will run my tests with the newer version of protoDC2 catalogues and post the plots here. I will also coordinate with @yymao to integrate this validation test into DESQA.

**Comment by aphearin** [comment]
Thanks for the update on the plots @Andromedanita. Could you remind me of the density of the CMASS catalog you have been comparing to?

**Comment by Andromedanita** [comment]
@aphearin  The CMASS catalogue has the density of 101/sq degree as @rmandelb  mentioned. It is on table 2 of http://adsabs.harvard.edu/abs/2016MNRAS.455.1553R

**Comment by aphearin** [comment]
Hmm, ok, so factor of 6 difference. Is it possible that there is tension between this number density measurement and the Moustakas+13 PRIMUS SMF measurements [plotted above](https://github.com/LSSTDESC/descqa/issues/109#issuecomment-388809084)?

**Comment by rmandelb** [comment]
@Andromedanita - thanks for sharing these numbers and plots.  Have you looked at the redshift distribution of these CMASS-like galaxies to see how it compares with the actual CMASS redshift distribution?  I wonder if that might shed some light on the matter.

**Comment by evevkovacs** [comment]
@aphearin @rmandelb @Andromedanita  The recent [dn/dmag](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-05-23_12&test=ApparentMagFuncTest_HSCi) test does not cover the range of magnitudes used in the above test. The catalog data is above the HSC extrapolation at i=23 by about 25%. It seems like it would be useful to extend the range plotted in the dn/dmag test so that we have a comparison available.

**Comment by aphearin** [comment]
@Andromedanita - could you confirm whether the following selection criteria stated in [your previous post](https://github.com/LSSTDESC/descqa/issues/109#issuecomment-388190268) are the defining cuts used to make a CMASS-analog for direct comparison with the number density quoted in [the BOSS paper](http://adsabs.harvard.edu/abs/2016MNRAS.455.1553R) that @rmandelb pointed us to?

1. d_perp < 0.55 where d_perp = (r-i) - (g-r)/8
2. i < 19.86 + 1.6(d_perp - 0.8)
3. 17.5 < i < 19.9
4. r-i < 2

If that's the correct criteria, that's easy for me to implement myself, so you can ignore [my previous request for code](https://github.com/LSSTDESC/descqa/pull/47#issuecomment-392083641).

**Comment by Andromedanita** [comment]
@aphearin Yes, those are the cuts I used and the cuts applied in CMASS selection criteria. They are stated in section 3.3 of this paper: http://adsabs.harvard.edu/abs/2016MNRAS.455.1553R

I have also cleaned my notebook and made it lsst readable on NERSC so that  it can be checked for any possible typos and the path to it is:
/global/homes/a/anitab/DESQA_Mstellar_issue_protoDC2_CMASS.ipynb

**Comment by aphearin** [comment]
Thanks a lot @Andromedanita - this is very helpful for the calibration I'm doing at the moment.

**Comment by aphearin** [comment]
This is great to see, @Andromedanita! We have come a long way since a factor of 600% discrepancy, no? We have been trying to maintain this number density manually, but @evevkovacs and @dkorytov and I would definitely like to incorporate this into our standard set of DESCQA checks. 

Would it be straightforward for you to add a title to this figure showing the number densities you quoted for both the mock and also observed in CMASS?

**Comment by evevkovacs** [comment]
Thanks very much @Andromedanita. This looks very nice. If you can implement Andrew's suggestion, I think your test would be ready to incorporate into DESCQA.  Would you be interested in doing that? I am happy to help you. Please take a look on https://github.com/LSSTDESC/descqa
There are instructions (see item 4) and code examples.

**Comment by Andromedanita** [comment]
I will add a title that shows the number densities to the plot, @aphearin . 
Thanks @evevkovacs . I am interested in making my code ready to be incorporated into DESQA. I will let you guys know if there is any issues in doing so.
