### ISSUE TITLE
add a verification test for the galaxies in truth catalog

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/descqa#129]
[See this slide](https://docs.google.com/presentation/d/1xXuDLU-2S9bPO3awgSNbSTvGpiHhK_q6f38Sp6xfnmU/edit#slide=id.g3de8536c77_8_0) for context. We want to make sure the truth catalog faithfully reproduce the galaxies in the extragalactic catalog. This verification test will simply compare the galaxy properties in the truth catalog against the extragalactic catalog. 

Since both extragalactic and truth catalogs are now available in GCRCatalogs. This should be pretty straight-forward. 

(cc @fjaviersanchez @danielsf @jbkalmbach @katrinheitmann @evevkovacs)

**Comment by yymao** [comment]
I'll start to work on this. @danielsf, what magnitudes should we compare to in the extragalactic catalog? Unlensed but with host dust extinction?

**Comment by danielsf** [comment]
I am going to update the truth catalog to include lensing magnification.

Run 2.0 should also have both host and Milky Way dust extinction.  I am of the opinion that the truth catalog should include both of these effects, since we want to use it to validate the measured magnitudes coming out of the DM pipeline.  I am open to other opinions.
