### ISSUE TITLE
Make DESCQA compatible with new desc-python environment 

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/descqa#222]
Currently DESCQA's execution script directly uses a python executable.  This way, end users do not need to activate any environment for using DESCQA. 

The new desc-python environment lives in a shifter image, so DESCQA would need to be run within that `desc-python` shifter image. That may be ok but it requires users to first switch to that environment every time before running DESCQA. 

Probably @heather999 @evevkovacs and I should chat to see if we can identify a solution..

**Comment by heather999** [comment]
Hi - thanks for pointing this out. I might need more details about how descqa works both for users as well as the web interface.  I'm going through the documentation to learn what I can.
At NERSC, is this the current web interface installation? `/global/cfs/cdirs/lsst/www/descqa/v2` the `run_master.sh` seems to be locally updated to point directly to the installation on `/global/common` rather than using either `setup_current_python.sh` or `setup_old_python.sh` - that's fine, I just want to understand how these pieces fit together.  I want to think that having run_master start up the shifter environment would be comparable - so I started to play around with run_master.sh at NERSC in my own area. 

two options I can think of:
* descqa can use a locally installed desc-python on Cori
* run_master is updated to start up the shifter environment and then proceed with running of tests.

Following the [instructions for Contributing](https://github.com/LSSTDESC/descqa/blob/master/CONTRIBUTING.md), I see how to run_master.sh at the command line at NERSC.

I updated my copy and it seems able to start up the shifter env, run descqa with the requested parameters (or not) and then exits:

```
#!/bin/bash

# go to a subshell
(

# make sure all commands are executed
set -e

export PYTHON='python'

# set output directory
OUTPUTDIR="/global/cscratch1/sd/heatherk/descqa"

# to allow wildcards in arguments go to master.py
set -o noglob

# run master.py
CMD="import descqarun; descqarun.main()"

PARAM="$@"

shifter --image=lsstdesc/desc-python:prod bash -c "source /usr/local/py/etc/profile.d/conda.sh && conda activate desc  && python -E -c '$CMD' '$OUTPUTDIR' $PARAM" 

# end subshell
)
```
We should test this out further, but I think this will allow descqa to use the shifter env and should be invisible to the users.  Does the web interface use run_master.sh or it is just allow users to view previously executed test results?

I've been thinking about trying to trigger integration tests that run at NERSC via GH actions. That should be possible - so maybe in the future.. a new dev version of desc-python could trigger a descqa test..   

Also wanted to note that while reading some of the doc, I think some of the links (jupyter.nersc, rather than jupyter-dev) and instructions on the [Mock Catalog How-To](https://confluence.slac.stanford.edu/pages/viewpage.action?pageId=227167079) needs to be updated.   Happy to help fix that.

**Comment by yymao** [comment]
The DESCQA web app and execution script use different python environments. 

For the web app, it directly uses the python executable of `desc-python-webapps` in `/global/common/software/lsst` (see [here](https://github.com/LSSTDESC/descqa/blob/master/index.cgi#L1)). 

For the execution script, in the past it also used the `desc-python` python executable (see [here](https://github.com/LSSTDESC/descqa/blob/a5a7ed046e35812438674a372eeaeaf604ecc896/run_master.sh#L14)). We have now moved to using `setup_old_python.sh` (see [here](https://github.com/LSSTDESC/descqa/blob/master/run_master.sh#L10))

(Side note: the execution script in `/global/cfs/cdirs/lsst/www/descqa/v2` is outdated. People are not supposed to use the execution script there; only the DESCQA web app is being used in that location.)

@heather999 Are you also planning to move `desc-python-webapps` to shifter? If not, the web app part is not affected. 

For the execution script, it may be ok to start up the shifter environment in `run_master.sh` as @heather999 demonstrated. But I know that people tend to run `run_master.sh` multiple times in a row, and hence it would be better if the shifter environment can be set up only once to avoid overhead. Maybe there's a way that we can write `run_master.sh` so that its up the shifter environment if it's not already in it?

**Comment by heather999** [comment]
No need to modify `desc-python-webapps` - I don't think it necessarily needs to move to shifter.  Maybe in some future issue we want to talk about long term maintenance of the web app, but that's not an issue we need to deal with now.

Knowing how people use `run_master.sh` helps!  So right now, what i had suggested would just run one time in the shifter env and then exit, leaving the user back in their original env before running run_master.  We can modify that and check to see if we're already in the shifter env, if not, set it up and then leave the user in the shifter environment? Maybe that mode of running is set by a flag passed to `run_master.sh`? What would be the preferred default behavior?

**Comment by yymao** [comment]
Thanks @heather999. What you suggested ("check to see if we're already in the shifter env, if not, set it up and then leave the user in the shifter environment") sounds good to me.  But really @evevkovacs uses this most frequently so I am interested in hearing her opinion on this.

**Comment by evevkovacs** [comment]
TBH, I haven't paid much attention to this, so I'm just reading your posts to get a handle on how it works. If I understand correctly, there are several options
1) user is entirely responsible for setting up shifter environment
2) run_master.sh sets up the environment and then exits
3) run_master.sh checks to see if environment is set up, sets it up if not, then leaves the user in that environment on exit.
I think 3) is probably the most convenient, but I suggest that run_master.sh should print a final message saying something like "You are now in the shifter environment. Do xxx to exit". (I don't know what xxx is BTW,  so I suspect others don't either)

**Comment by yymao** [comment]
I think this issue can be closed now since the DESC Python environment is now installed on NERSC disks again (see #226). I think we may need to document somewhere so that in the future if the DESC Python environment is moving to shifter again, proper communication/discussion will take place before that happen (cc @heather999)
