### ISSUE TITLE
shear-shear correlation

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/descqa#35]
~For testing IA models~, it would be useful to test the 2-pt functions. We plan to use treecorr for the calculation. ~We plan to start with using analytical calculation as the validation dataset (@jablazek @patricialarsen).~  (Edited by Rachel to reflect the focus on cosmological shear-shear, not intrinsic alignments.)

- [x] code to reduce mock data
- [x] code that works within DESCQA framework
- [x] validation data
- [ ] validation criteria

**Comment by yymao** [comment]
It seems like @chihway has made much progress on this using the WLPipe during the Sprint Week. @chihway, can you post some plots here and then we can continue to make a validation test from what yu have done?

**Comment by patricialarsen** [comment]
Hi @yymao, I've been working on this - we don't have cosmosis on the descqa environment so it's not exactly the same validation test but I'm implementing a similar thing with the programs we have in the environment.

**Comment by patricialarsen** [comment]
@yymao @chihway : this will be more simple though and it would be great to do the proper analysis with the pipeline and the analysis tools we're using. Once I have the simple version implemented it would be easy to swap it out so I'm guessing setting up the environment to have these tools will be the main challenge to that.

**Comment by yymao** [comment]
Thanks @patricialarsen, do you want to share some plots here too? BTW, I couldn't assign you, please consider add your GitHub account to the DESC member directory.

**Comment by chihway** [comment]
Sorry guys just saw this, below are what I have for proto-DC2 and buzzard_test

![image](https://user-images.githubusercontent.com/2736097/33739027-2133c8bc-db61-11e7-91bf-eacaa041f7d1.png)

![image](https://user-images.githubusercontent.com/2736097/33739056-3d7de76e-db61-11e7-90e8-f089d2d8bdfe.png)

**Comment by katrinheitmann** [comment]
So Buzzard was run on the full area that's available, right? Thanks! (btw, somewhere it said that protoDC2 is 2.5x2.5, it's 5x5).

**Comment by chihway** [comment]
Buzzard was run on 'buzzard_test' in gcr which is one healpix (~50 deg^2?) tile. 

And yeah sorry I must have mis-written the area. Yes 5x5.

**Comment by yymao** [comment]
I think this is Buzzard_test, so is only 53.7 sq. deg.

**Comment by EiffL** [comment]
@patricialarsen @chihway @jablazek It sounds to me that this issue actually covers 2 different things: IA pt functions tests  and  WL 2pt functions. I'm proposing opening another issue where I am going to implement the Ellipticity-Direction correlation function if that's ok with you guys

**Comment by yymao** [comment]
@EiffL that sounds a good idea. @chihway, should I rename this to validation for WLPipe, and open a new issue for @patricialarsen, @EiffL, and @jablazek on the Ellipticity-Direction correlation?

**Comment by jablazek** [comment]
this seems sensible to me. The necessary 2pt codes are similar but not the same.

**Comment by chihway** [comment]
Yep sounds good to me!

**Comment by patricialarsen** [comment]
Just to keep this issue updated: a first draft of shear-shear 2pt correlations is in the pull request labelled "first commit of shear test" (https://github.com/LSSTDESC/descqa/pull/54) 

This doesn't use WLPipe yet, but a simple theory code. It is very preliminary and will be updated over the coming weeks, but currently plots 2pt shear correlation functions from the simulation data against theory within the DESCQA framework.

**Comment by patricialarsen** [comment]
In response to @rmandelb (comment below)

The main difference between the shear-shear validation test plots and @chihway's plot is that the theory she used was from WLPipe. It would be great to incorporate that theory, but it's not in the descqa environment on nersc so I'm using a simpler theory code based on the camb module that is in the environment. We could try to get it installed properly but it's only worthwhile if we require high accuracy at the validation test stage. 

Effectively the update on the test is that a simple version for making the plots and comparing with theory is ready to go, but we need validation criteria to determine if they pass/fail the test, and some extensions like using tomography or comparing shear/convergence can also be implemented fairly quickly depending on requirements. 


# original comment

@patricialarsen - I wanted to touch base with you about this validation test. A few questions:

You mentioned that this test is for lensing as well as for IAs. If so, I think it would be worth splitting into two tests because they are testing rather different things for which our validation criteria will differ quite a bit. Do you agree, and if so, could you think about the proper split to make and open a new issue/issues as appropriate?

I know that @chihway had done some tests of shear-shear correlations already, and I wanted to know if you have seen that work and might consider incorporating some of it? (or whether there was some obstacle to doing that)

An update on the status of this test / these tests would be useful.

**Comment by yymao** [comment]
Implemented in #54
