### ISSUE TITLE
finalize the acceptable quantity ranges for the readiness test on protoDC2

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/descqa#60]
Now that we have a readiness test in place (you can [see a demo here](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-01-18_9&test=readiness_protoDC2&right=2018-01-18_9/readiness_protoDC2/protoDC2/SUMMARY.html)), we need to finalize the acceptable ranges for each quantities in protoDC2, especially those used by the image generation. 

All the acceptable ranges are set in [this YAML config file](https://github.com/LSSTDESC/descqa/blob/master/descqa/configs/readiness_protoDC2.yaml). @evevkovacs and I have put in many quantities, but I don't think we have exhaust them. Some of them do not have have acceptable ranges specified. 

Once this is done, it means we can sign off protoDC2 2.1.2. I assign this to @evevkovacs and @dkorytov but I think we might also need help from @danielsf and @abensonca. Also cc'ing @rmandelb @katrinheitmann @jchiang87 for their information.

**Comment by jchiang87** [comment]
Sorry, I haven't been trying to follow the discussion on these validation tests very closely, and I'll admit to not understanding the relationship between "true" and non-"true" quantities, so apologies if this has been discussed or doesn't make sense:   Since you are overlaying distributions of things like redshift with redshift_true, I assume this implies these distributions should be consistent with each other at some level.  Have you considered including statistics like KS or chi-square on the binned data?  Certainly checking that the summary statistics are within bounds for each distribution will do some checking of internal consistency, but direct comparisons using relevant statistics might catch something that the range checks of the summary stats could miss.

**Comment by yymao** [comment]
@jchiang87  "true" and "non-true" quantities are before and after lensing effect, so they should be similar but not identical. The "true" quantities are not validation data. 

Quantities that are plotted on the same plot just have similar ranges, so it's easy for visual inspection. That does not mean we are comparing the quantities against each other on the same plot.

**Comment by evevkovacs** [comment]
@jchiang We struggled with a method to automate the readiness test, but decided that human intervention was needed. So the basic idea is that the catalog providers run this test to make sure that the values in the catalog are reasonable, and that the distributions pass a visual inspection. The providers will then "sign-off" (location TBD) that the version of the catalog has "passed".

**Comment by salmanhabib** [comment]
@jchiang87 There was a lot of discussion regarding error metrics for the validation tests. The basic problem is that unless catalogs are tuned to observations, the deviations are systematically off and tests like KS and chi^2 are not really sufficiently informative. For example, one catalog may be fine for a certain limited range of observables and deviate outside this range, but may be the science case is ok for this range, so the catalog is still ok for this limited purpose. Or maybe, the data is good almost everywhere but has some artifacts that are problematic, etc. So, in the end, we just left it to people to decide -- 

But I agree we need to return to this point in the future.
