### ISSUE TITLE
Radial profiles of red-sequence cluster members

### ISSUE THREAD

**Issue by j-dr** [LSSTDESC/descqa#63]
Moving the conversation started in #10 here. The idea is that we would like to make sure that the CL WG goal of investigating miscentering in DC2 is possible by validating the radial profiles of cluster members. 

One way to do this is just to directly measure the radial profiles in cluster mass halos. This should be easy to implement, but is going to be difficult to compare to data, since and profiles measured there will have significant projection effects. 

The other thing to do is to measure color dependent clustering, which will be easier to find validation data for, but less directly tests what we care about.

Opinions @rmandelb @aphearin @yymao @erozo @anjavdl?

**Comment by erozo** [comment]
I think halo--galaxy CF in a color bin would be great.  I also think the PDF of "# counts of red galaxies in  1 Mpc around random points" relative to "# counts of red gals around halos of a given mass" would be a useful thing to look at.

**Comment by aphearin** [comment]
halo--galaxy CF does not address "the problem of having to run RedMapper" (phrase coined by @rmandelb). Galaxy clustering is a lot more observationally robust. As a catalog producer, I myself would not pay much attention to such a test unless RedMapper were first run on the mock to identify the "halos" (at which point I would pay close attention to it). 

If radial profiles of some variety are needed, and the validation can be done on a snapshot catalog with a periodic box, the [radial_profile_3d](http://halotools.readthedocs.io/en/latest/api/halotools.mock_observables.radial_profile_3d.html) Halotools function may be useful

**Comment by aphearin** [comment]
Here is an example plot of color-dependent clustering at z=0.1, taken from the overhauled DC2 I have been working on. For luminosity thresholds ~<-20.5, everything looks good on all scales. Going down as faint as -19 causes some problems that are primarily due to pushing up against the resolution limits of the simulation. 

![two_panel_color_clustering](https://user-images.githubusercontent.com/6951595/35254016-06e5785e-ffae-11e7-9ccc-c86c3fe5f33a.jpg)

Luminosity-dependent clustering at z=0.1 now looks good as well:

![four_panel_luminosity_clustering](https://user-images.githubusercontent.com/6951595/35254051-3efc5474-ffae-11e7-8f40-f7890a894416.jpg)

**Comment by rmandelb** [comment]
@j-dr @erykoff - I wanted to touch base with you about this validation test of cluster member galaxy radial profiles that Joe opened.  In the conversation on this thread, two approaches were discussed:

1. Measure radial profiles of galaxies in clusters (running redmapper on the catalog first).  Some care would be needed to select a validation dataset.

2. Use color-dependent clustering validated against SDSS.  This is a more indirect test, but its primary virtue (in my opinion) is that there is good validation data with less ambiguity about how to compare data vs. sims. @aphearin kindly provided a plot in this issue, in the comment just above this one, so you can see what that might look like.

Can you please try to converge in the next day on which approach to take, bearing in mind that we need all of the following to be defined?
- the method of carrying out the test (i.e. exactly what must be measured in the sims)
- a validation dataset
- a validation criterion
- a decision as to whether this is a required test for the CL working group
If you go with option (2), it seems Andrew has done the first two of those steps for you already.

**Comment by j-dr** [comment]
I think color-dependent clustering is the way to go. It has the important benefit of having readily available validation data and doesn't require running redmapper (although I think we're going to have to do this for at least one other test anyways). 

The test that @aphearin has implemented should do just fine. It might be useful to also include a higher redshift measurement, e.g. from [0708.0004](https://arxiv.org/pdf/0708.0004.pdf). 

If this is going to be required I think we need to target the criteria at the brighter luminosity bins, since these are going to be most important for centering studies, and fainter luminosity bins are going to be quite challenging given the resolution of the sim. I think the -20.5 plot that Andrew posted should already satisfy any validation criteria that I would give. @erykoff, @erozo, @anjavdl what do you think?

**Comment by rmandelb** [comment]
@j-dr - it's true that we'll have to run redmapper for another test.  But I think this color-dependent clustering test is quite useful and it'll help other groups as well.

I like your idea of having a higher redshift data point.  Figure 9 in the paper you linked to might be the one to use.

Let me suggest that since others may be interested in this, we implement the test such that fainter luminosities are still shown, even if the validation criterion is imposed only on the bright end.  We should think about precisely what our requirement is going to be on the red vs. blue wp(rp) comparison.  Just for the sake of simplicity, we could multiply them by rp to get something that is nearly flat, and compare <rp * wp> (averaged from say 0.5-10 Mpc) for red against the same quantity for blue.  Does this make sense?  Or we could fit to a power law and place a validation criterion on both the red vs. blue slope, and red vs. blue amplitude at some fiducial rp value.

I believe we still need somebody to implement this in DESCQA, since the above plots from Andrew are a good starting point but are not (as far as I know) integrated into DESCQA.  Might you be willing to solicit volunteers from CL, and if you don't get anybody, we can call this out as a hack day project at the extragalactic catalog validation session?

**Comment by yymao** [comment]
@j-dr @aphearin @rmandelb should we rename this test to color-dependent galaxy clustering? Or open a new issue for color-dependent galaxy clustering? 

I guess the answer depends on whether or not we still need to test radial profile of red-sequence cluster members. I think this requires redMapper, right? 

I propose we open a new issue for color-dependent galaxy clustering, and keep this one focusing on testing the radial profile after (or if) redMapper is run. Does that sound good?

**Comment by j-dr** [comment]
Yeah, I think we should just open a new issue for color dependent clustering. I don't think we currently plan on testing radial profiles aside from what will be implemented there, at least for DC2, nevertheless I think it's good to keep these issues very specific.

**Comment by yymao** [comment]
This test has been suppressed by #73.
